### PR TITLE
fix the path issues for the gulp tasks for the scss and fonts.

### PR DESCRIPTION
**Pull request by agnellvj**

### CODE REVIEW

**Comment by agnellvj** [comment]
@jbavari @mlynch

**Comment by jbavari** [comment]
Hey @agnellvj - Thank you for the pull request.

We are no longer using gulp out of the box. For now, we are removing it. Try updating your CLI to the latest alpha tag: `npm install -g ionic@alpha` - we are now building things without gulp, but rather, with the CLI.

**Comment by agnellvj** [comment]
ah gotcha, the documentation says to use gulp though...

**Comment by jbavari** [comment]
Reopening:

Update docs - put directions for current CLI build process

**Pull request closed without merging**
